version: "3.8"

services:
  db:
    image: mysql:8.0.22
    restart: always
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./mysql.env
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1 FROM DUAL;"
      interval: 3s
      timeout: 3s
      retries: 30
  backend:
    build:
      context: ./backend
    env_file:
      - ./app.env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
    - 8000:8000
    entrypoint: /wait-for-it.sh db:3306 -- uwsgi --ini backend/web/uwsgi.ini

volumes:
  mysql-data: